Make `TPrintLowPri#default` an old-style implicit
to avoid the following error:
```
trait TPrintLowPri:
  inline given default[T]: TPrint[T] = ???

object TPrint extends TPrintLowPri:
  implicit val NothingTPrint: TPrint[Nothing] = ???

object TPrintTests extends TestSuite:
  ...
-- [E172] Type Error: /__w/scala3/scala3/community-build/community-projects/PPrint/pprint/test/src-3/test/src/pprint/TPrintTests.scala:42:40
Error:  42 |        test - check[Nothing]("Nothing")
Error:     |                                        ^
Error:     |Ambiguous given instances: both value NothingTPrint in object TPrint and given instance default in trait TPrintLowPri match type pprint.TPrint[Nothing] of parameter tprint of method check in object TPrintTests
```

The `implicit val` used to beat the `given def`
since `TPrintLowPri` is a super trait of `TPrint`.
In addition, b644d303e08bfa4b70498df7d3c170ec3889376c made givens beat implicits,
which created the ambiguity.

A simple fix to the community-project for now, to allow merging #21226,
is to fall back to an old-style implicit for `TPrintLowPri#default`.